name: powersync_flutter_demo
description: PowerSync Flutter Demo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  powersync: ^0.4.0
  path_provider: ^2.0.12
  supabase_flutter: ^1.6.2
  path: ^1.8.2
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
